@Library('Shared') _
pipeline {
    agent any
    
    parameters {
        string(name: 'DOCKER_TAG', defaultValue: '', description: 'Docker tag of the image built by the CI job')
    }

    stages {
        stage("Workspace cleanup"){
            steps{
                script{
                    cleanWs()
                }
            }
        }
        
        stage('Git: Code Checkout') {
            steps {
                script{
                    code_checkout("https://github.com/DevMadhup/Springboot-BankApp.git","DevOps")
                }
            }
        }
        
        stage('Verify: Docker Image Tags') {
            steps {
                script{
                    echo "DOCKER TAG RECEIVED: ${params.DOCKER_TAG}"
                }
            }
        }
        
        
        stage("Update: Kubernetes manifest"){
            steps{
                script{
                    dir('k8s'){
                        sh """
                            sed -i -e s/springboot-bankapp.*/springboot-bankapp:${params.BACKEND_DOCKER_TAG}/g deployment.yml
                        """
                    }
                }
            }
        }
        
        stage("Git: Code update and push to GitHub"){
            steps{
                script{
                    withCredentials([gitUsernamePassword(credentialsId: 'Github-cred', gitToolName: 'Default')]) {
                        sh '''
                        echo "Checking repository status: "
                        git status
                    
                        echo "Adding changes to git: "
                        git add .
                        
                        echo "Commiting changes: "
                        git commit -m "Updated K8s Deployment Docker Image Version"
                        
                        echo "Pushing changes to github: "
                        git push https://github.com/DevMadhup/Springboot-BankApp.git DevOps
                    '''
                    }
                }
            }
        }
    }
  post {
        always {
            script {
                emailext attachLog: true,
                from: '8007930568pandey@gmail.com',
                subject: "BankApp Application has been updated and deployed - '${currentBuild.result}'",
                body: """
                    <html>
                    <body>
                        <div style="background-color: #FFA07A; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">Project: ${env.JOB_NAME}</p>
                        </div>
                        <div style="background-color: #90EE90; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">Build Number: ${env.BUILD_NUMBER}</p>
                        </div>
                        <div style="background-color: #87CEEB; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">URL: ${env.BUILD_URL}</p>
                        </div>
                    </body>
                    </html>
            """,
            to: '8007930568pandey@gmail.com',
            mimeType: 'text/html'
            }
        }
    }
}